[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test/solidity/"
solc = "0.8.19"
gas_limit = 3_000_000      # fixed gas limit
tx_type = 0                # legacy Tx

[rpc_endpoints]
kurtosis = "${RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
